# Generated by Django 5.2.4 on 2025-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250808_1620'),
    ]

    operations = [
        # Corriger le champ promo_code pour qu'il soit optionnel
        migrations.AlterField(
            model_name='reservation',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
