# Generated by Django 5.2.4 on 2025-08-08 22:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250808_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='agency_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_reservations', to='core.agency'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='agency_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_reservations', to='core.agency'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='driver_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
